services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zk
    environment:
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zk_data:/bitnami
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      # core wiring
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_IP}:9092,PLAINTEXT_INTERNAL://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      # single-broker lab sanity (avoid unmet replica requirements)
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      # lower resource footprint for Pi lab
      - KAFKA_CFG_NUM_PARTITIONS=3
    ports:
      - "9092:9092" # exposed to your LAN/laptop
    volumes:
      - kafka_data:/bitnami
    restart: unless-stopped

volumes:
  zk_data:
  kafka_data:
